/** Shared route list for sitemap generation and build-time prerender. */
export const SITE_ROUTES = [
  "/",
  "/emdr-therapy",
  "/panic-attacks",
  "/phobias",
  "/anxiety",
  "/grief",
  "/divorce",
  "/sexual-abuse",
  "/emotional-abuse",
  "/eating-disorders",
  "/psychosomatics",
  "/business-psychology",
  "/ptsd",
  "/ocd",
  "/burnout",
  "/dissociation",
  "/complex-ptsd",
  "/parents-relationship",
  "/emigration-stress",
  "/privacy",
  "/privacy-policy",
  "/offer",
  "/advertising-consent",
];
